//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaviCURDWebApp.DB_Connect_RP
{
    using System;
    using System.Collections.Generic;
    
    public partial class stud_info
    {
        public int Std_id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string City { get; set; }
        public string email { get; set; }
        public string country { get; set; }
    }
}
